amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.1
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.2
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 0.5
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0

bt_navigator:
  ros__parameters:
    use_sim_time: True
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - "nav2_compute_path_to_pose_bt_node"
    - "nav2_follow_path_bt_node"
    - "nav2_back_up_bt_node"
    - "nav2_spin_bt_node"
    - "nav2_wait_bt_node"
    - "nav2_clear_costmap_bt_node"

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      lookahead_dist: 0.6
      min_lookahead_dist: 0.3
      max_lookahead_dist: 0.9
      speed: 0.5
      rotate_to_heading_angular_speed: 0.8
      transform_tolerance: 0.2
      use_velocity_scaled_lookahead_dist: True
      scaled_lookahead_time: 1.5
      min_lookahead_time: 0.5
      max_lookahead_time: 2.0
      desired_linear_vel: 0.5
      base_frame_id: "base_link"
      odom_topic: "odom"
      use_rotate_to_heading: True

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      plugin_names: ["obstacle_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      footprint: "[[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]"
      inflation_layer:
        cost_scaling_factor: 10.0
        inflation_radius: 0.55

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      plugin_names: ["obstacle_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      footprint: "[[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]"
      inflation_layer:
        cost_scaling_factor: 10.0
        inflation_radius: 0.55

